<?php

/**
 * @file
 * Alters the menu item form to allow the administrator to specify additional
 * attributes for the menu link
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;

define('MENU_ATTRIBUTES_LINK', 'attributes');
define('MENU_ATTRIBUTES_ITEM', 'item_attributes');


/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function menu_attributes_menu_link_content_presave(EntityInterface $entity) {
  $item = $entity->toArray();
  if (isset($item['options']['attributes']) && is_array($item['options']['attributes'])) {
    // Filter out blank attributes.
    foreach ($item['options']['attributes'] as $key => $value) {
      if ((is_array($value) && empty($value)) || is_string($value) && !Unicode::strlen($value)) {
        unset($item['options']['attributes'][$key]);
      }
    }

    // Convert classes to an array.
    if (isset($item['options']['attributes']['class']) && is_string($item['options']['attributes']['class'])) {
      $item['options']['attributes']['class'] = array_filter(explode(' ', $item['options']['attributes']['class']));
    }
  }
}

/**
 * Implements hook_menu_attribute_info().
 */
function menu_attributes_menu_attribute_info() {
  $info['title'] = [
    'label' => t('Title'),
    'description' => t('The description displayed when hovering over the link.'),
    'form' => [
      '#type' => 'textarea',
      '#rows' => 2,
    ],
    'scope' => [MENU_ATTRIBUTES_LINK],
  ];
  $info['id'] = [
    'label' => t('ID'),
    'description' => t('Specifies a unique ID for the link.'),
    'scope' => [MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM],
  ];
  $info['name'] = [
    'label' => t('Name'),
    'scope' => [MENU_ATTRIBUTES_LINK],
  ];
  $info['rel'] = [
    'label' => t('Relationship'),
    'description' => t("Specifies the relationship between the current page and the link. Enter 'nofollow' here to nofollow this link."),
    'scope' => [MENU_ATTRIBUTES_LINK],
  ];
  $info['class'] = [
    'label' => t('Classes'),
    'description' => t('Enter additional classes to be added to the link.'),
    'scope' => [MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM],
  ];
  $info['style'] = [
    'label' => t('Style'),
    'description' => t('Enter additional styles to be applied to the link.'),
    'scope' => [MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM],
  ];
  $info['target'] = [
    'label' => t('Target'),
    'description' => t('Specifies where to open the link. Using this attribute breaks XHTML validation.'),
    'form' => [
      '#type' => 'select',
      '#options' => [
        '' => t('None (i.e. same window)'),
        '_blank' => t('New window (_blank)'),
        '_top' => t('Top window (_top)'),
        '_self' => t('Same window (_self)'),
        '_parent' => t('Parent window (_parent)'),
      ],
    ],
    'scope' => [MENU_ATTRIBUTES_LINK],
  ];
  $info['accesskey'] = [
    'label' => t('Access Key'),
    'description' => t('Specifies a <a href=":accesskey">keyboard shortcut</a> to access this link.', [':accesskey' => Url::fromUri('http://en.wikipedia.org/wiki/Access_keys')]),
    'form' => [
      '#maxlength' => 1,
      '#size' => 1,
    ],
    'scope' => [MENU_ATTRIBUTES_LINK],
  ];
  return $info;
}

/**
 * Fetch an array of menu attributes.
 */
function menu_attributes_get_menu_attribute_info() {
  $module_handler = \Drupal::moduleHandler();
  $attributes = $module_handler->invokeAll('menu_attribute_info');
  $config = \Drupal::config('menu_attributes.settings');
  // Merge in default values.
  foreach ($attributes as $attribute => &$info) {
    $info += [
      'form' => [],
      'enabled' => $config->get('attribute_enable.{$attribute}'),
      '#default_value' => $config->get('attribute_enable.' . $attribute),
    ];
    $info['form'] += [
      '#type' => 'textfield',
      '#title' => $info['label'],
      '#description' => isset($info['description']) ? $info['description'] : '',
      '#default_value' => $config->get('attribute_default.' . $attribute),
    ];
  }
  $module_handler->alter('menu_attribute_info', $attributes);

  return $attributes;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds menu attribute options to the edit menu item form.
 *
 * @see _menu_attributes_form_alter()
 * @see menu_attributes_form_menu_edit_item_submit()
 */
function menu_attributes_form_menu_link_edit_alter(&$form, FormStateInterface $form_state) {
  _menu_attributes_form_alter($form, $form, $form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds menu attribute options to the node's edit menu item form.
 *
 * @see _menu_attributes_form_alter()
 */
function menu_attributes_form_node_form_alter(&$form, FormStateInterface $form_state) {
  if (isset($form['menu']['link']) && isset($form['#node']->menu)) {
    $item = $form['#node']->menu;
    _menu_attributes_form_alter($form['menu']['link'], $form['menu']['link'], $form);
  }
}

/**
 * Add the menu attributes to a menu item edit form.
 *
 * @param $form
 *   The menu item edit form passed by reference.
 * @param $item
 *   The optional existing menu item for context.
 */
function _menu_attributes_form_alter(array &$form, array $item = [], array &$complete_form) {
  $form['options']['#tree'] = TRUE;
  $form['options']['#weight'] = 50;

  // Unset the previous value so that the new values get saved.
  unset($form['options']['#value']['attributes']);
  unset($form['options']['#value']['item_attributes']);

  $form['options'][MENU_ATTRIBUTES_LINK] = [
    '#type' => 'details',
    '#title' => t('Menu link attributes'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  ];

  $form['options'][MENU_ATTRIBUTES_ITEM] = [
    '#type' => 'details',
    '#title' => t('Menu item attributes'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  ];

  $attributes = menu_attributes_get_menu_attribute_info();
  foreach ($attributes as $attribute => $info) {
    // If no scope is set, this attribute should be available to both link
    // and item.
    if (!isset($info['scope'])) {
      $info['scope'] = [MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM];
    }

    // Define fields for each scope.
    foreach ($info['scope'] as $group) {
      // Merge in the proper default value.
      if (isset($item['options'][$group][$attribute])) {
        // If the menu link already has this attribute, use it.
        $info['form']['#default_value'] = $item['options'][$group][$attribute];
        // Convert the classes array to a string for the form.
        if ($attribute == 'class' && is_array($info['form']['#default_value'])) {
          $info['form']['#default_value'] = implode(' ', $info['form']['#default_value']);
        }
      }
      elseif ($item['mlid']) {
        // If this is an existing link, use the raw default (usually empty).
        $info['form']['#default_value'] = $info['default'];
      }
      $form['options'][$group][$attribute] = $info['form'] + [
        '#access' => $info['enabled'],
        ];
    }
  }

  // Add form values for the reset of $item['options'] and
  // $item['options']['attributes'] so the values will carry over during save.
  foreach ($item['options'] as $key => $value) {
    if ($key !== 'attributes' && !isset($form['options'][$key])) {
      $form['options'][$key] = [
        '#type' => 'value',
        '#value' => $value,
      ];
    }
  }
  foreach ([MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM] as $group) {
    if (isset($item['options'][$group])) {
      foreach ($item['options'][$group] as $key => $value) {
        if (!isset($form['options'][$group][$key])) {
          $form['options'][$group][$key] = [
            '#type' => 'value',
            '#value' => $value,
          ];
        }
      }
    }
  }

  // Hide the 'description' field since we will be using our own 'title' field.
  if (isset($form['description'])) {
    $form['description']['#access'] = FALSE;

    // Because this form uses a special $form['description'] field which is
    // really the 'title' attribute, we need to add special pre-submit handling
    // to ensure our field gets saved as the title attribute.
    array_unshift($complete_form['#submit'], '_menu_attributes_form_submit');
  }

  // Restrict access to the new form elements.
  $has_visible_children = (bool) Element::getVisibleChildren($form['options']['attributes']);
  $user_has_access = \Drupal::currentUser()->hasPermission('administer menu attributes');
  $form['options']['attributes']['#access'] = ($has_visible_children && $user_has_access);
}

/**
 * Form submit handler for menu item links.
 *
 * Move the title attributes value into the 'description' value so that it
 * will get properly saved.
 */
function _menu_attributes_form_submit($form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  if (isset($values['menu']['options']['attributes']['title'])) {
    $values['menu']['description'] = $values['menu']['options']['attributes']['title'];
  }
  elseif (isset($values['options']['attributes']['title'])) {
    $values['description'] = $values['options']['attributes']['title'];
  }
}

/**
 * Implements MODULE_preprocess_HOOK().
 *
 * Adds appropriate attributes to the list item.
 *
 * @see theme_menu_link()
 */
function menu_attributes_preprocess_menu_link(&$variables) {
  $options = &$variables['element']['#localized_options'];
  $attributes = &$variables['element']['#attributes'];

  if (isset($options['item_attributes'])) {
    foreach ($options['item_attributes'] as $attribute => $value) {
      if (!empty($value)) {
        // Class get's special treatment, as it's an array and it should not
        // replace existing values.
        if ($attribute == 'class') {
          $value = explode(' ', $value);
          if (isset($attributes[$attribute])) {
            $value = array_merge($attributes[$attribute], $value);
          }
        }
        // Override the attribute.
        $attributes[$attribute] = $value;
      }
    }

    // Clean up, so we're not passing this to l().
    unset($options['item_attributes']);
  }
}
